name: C/C++ CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
      fail-fast: false

    steps:
    - uses: actions/checkout@v6

    - name: Setup GCC
      if: matrix.compiler == 'gcc'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest

    - name: Setup Clang
      if: matrix.compiler == 'clang'
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest

    - name: List Dir (before build)
      run: find . -type f | sort

    - name: Configure with CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: List Dir (after build)
      run: find . -type f | sort

    - name: Install
      run: cmake --install build --prefix install

    - name: List install dir
      run: find install -type f | sort

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: myprogram-${{ matrix.compiler }}
        path: install/
